### ISSUE TITLE
Call to abstract method...

### ISSUE THREAD

**Issue by dailytabs** [kravietz/java-saml-validator#1]
java.lang.AbstractMethodError: javax.xml.parsers.DocumentBuilderFactory.setFeature(Ljava/lang/String;Z)V
    __redirected.__DocumentBuilderFactory.setFeature(__DocumentBuilderFactory.java:179)
    ....Validator.validate(Validator.java:148)

Seriously?

**Comment by dailytabs** [comment]
Pulling in xercesImpl fixed this.

```
<dependency>
    <groupId>xerces</groupId>
    <artifactId>xercesImpl</artifactId>
    <version>2.11.0</version>
</dependency>
```

However, 2.11.0 doesn't seem to support several attributes/features:

```
java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
```

Fixed by commenting out the `factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, "file,jar");` line.

```
java.lang.IllegalArgumentException: Property 'http://javax.xml.XMLConstants/property/accessExternalSchema' is not recognized.
```

Fixed by commenting out the `factory.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "file,jar");` line.

```
Unsupported XML parser feature http://xml.org/sax/features/unicode-normalization-checking
```

Fixed by commenting out the `hm.put("http://xml.org/sax/features/unicode-normalization-checking", true);` line.

EntityResolver also had issues finding the local schemata, due to a missing leading "/". Fixed lines look like `file = "/saml/schemas/xml.xsd";`.

Essentially, I had to fork this project and heavily modify it to work. Hope this helps to either fix other people's issues or to discourage them from using this library.

**Comment by kravietz** [comment]
Hi, the compilation errors are strange as I was using this code in production for a while on JDK8 a year ago with standard built-in XML parser. File paths might be broken as I was replacing the ones from my proprietary code into a dummy ones.

**Comment by kravietz** [comment]
If you have forked the code can you create a pull request? I will recompile this on a new environment from scratch to see what might be causing the problems.

**Comment by dailytabs** [comment]
Ahhhh! That explains it. I have to use and was using Java 7.

Sorry to bother you.

**Comment by kravietz** [comment]
No problem - I was quite surprised as I've never seen these errors when compiled it myself. Sorry for the trouble, if manage to get it working you might still want to create a pull request. On JDK7 however it might be challenging as I remember using some of the JDK8 features for improved security (like the XML parser flags).
